from .typeclass import *
from .functor import *
from .applicative import *
from .monad import *
from .contravariant import *
from .profunctor import *
from .cartesian import *
from .cocartesian import *
from .monoid import *
from .foldable import *
from .patternmatchable import *
from .hashable import *
